(defun ext-v-full (ext-v) (format "ext-%s" ext-v))

(defun env-evt-gen (ext-v)
  (interactive)
  (setenv "CLHEP_INCLUDE_DIR" (format "%s/%s/include/geant4" pnd-dir (ext-v-full ext-v)))
  (setenv "CLHEP_LIBRARY_DIR" (format "%s/%s/lib" pnd-dir (ext-v-full ext-v)))
  (setenv "CLHEP_BASE_DIR" "")
  (setenv "PLUTO_LIBRARY_DIR" (format "%s/%s/lib" pnd-dir (ext-v-full ext-v)))
  (setenv "PLUTO_INCLUDE_DIR" (format "%s/%s/include/pluto" pnd-dir (ext-v-full ext-v)))
  (setenv "PYTHIA6_LIBRARY_DIR" (format "%s/%s/lib" pnd-dir (ext-v-full ext-v)))
  (setenv "PYTHIA8DATA" (format "%s/%s/share/pythia8/xmldoc" pnd-dir (ext-v-full ext-v))))

(defun env-geant-3 (ext-v)
  (interactive)
  (setenv "G3SYS" (format "%s/%s/share/geant3" pnd-dir (ext-v-full ext-v)))
  (setenv "GEANT3_INCLUDE_DIR" (format "%s/%s/include/TGeant3" pnd-dir (ext-v-full ext-v)))
  (setenv "GEANT3_LIBRARY_DIR" (format "%s/%s/lib" pnd-dir (ext-v-full ext-v)))
  (setenv "GEANT3_LIBRARIES" (format "%s/%s/lib/libgeant321.so" pnd-dir (ext-v-full ext-v))))

(defun env-geant-4-dat (ext-v)
  (interactive)
  (let ( (dat-dir (format "%s/%s/share/Geant4/data" pnd-dir (ext-v-full ext-v))) )
    (setenv "G4LEDATA" (format "%s/G4EMLOW" dat-dir))
    (setenv "G4LEVELGAMMADATA" (format "%s/PhotonEvaporation" dat-dir))
    (setenv "G4NeutronHPCrossSections" (format "%s/G4NDL" dat-dir))
    (setenv "G4NEUTRONHPDATA" (format "%s/G4NDL" dat-dir))
    (setenv "G4NEUTRONXSDATA" (format "%s/G4NEUTRONXS" dat-dir))
    (setenv "G4PIIDATA" (format "%s/G4PII" dat-dir))
    (setenv "G4RADIOACTIVEDATA" (format "%s/RadioactiveDecay" dat-dir))
    (setenv "G4REALSURFACEDATA" (format "%s/RealSurface" dat-dir))
    (setenv "G4SAIDXSDATA" (format "%s/G4SAIDDATA" dat-dir))))

(defun env-geant-4 (ext-v)
  (interactive)
  (setenv "GEANT4_LIBRARY_DIR" (format "%s/%s/lib" pnd-dir (ext-v-full ext-v)))
  (let* ( (g4-dir (format "%s/%s/transport/geant4" pnd-dir (ext-v-full ext-v) ))
	  (had-dir (format "%s/physics_lists/hadronic" g4-dir )) )
    (setenv "GEANT4_INCLUDE_DIR"
	    (concat (format "%s/%s/include/geant4:" pnd-dir (ext-v-full ext-v))
		    (format "%s/source/interfaces/common/include:" g4-dir)
		    (format "%s/Packaging/include:" had-dir)
		    (format "%s/QGSP/include" had-dir)))))

(defun env-vmc (ext-v)
  (interactive)
  (let* ( (ext-dir (format "%s/%s" pnd-dir (ext-v-full ext-v)))
	  (trans-dir (format "%s/transport" ext-dir)) )
    (setenv "GEANT4VMC_INCLUDE_DIR" (format "%s/geant4_vmc/include/geant4vmc" trans-dir))
    (setenv "GEANT4VMC_LIBRARY_DIR" (format "%s/lib" ext-dir))
    (setenv "GEANT4VMC_MACRO_DIR"  (format "%s/macro" trans-dir)))
  (setenv "CLASSAPTH" "")
  (setenv "USE_VGM" "1"))

(defun env-root (ext-v)
  (interactive)
  (setenv "ROOTSYS" (format "%s/%s" pnd-dir (ext-v-full ext-v)))
  (setenv "ROOT_LIBRARY_DIR" (format "%s/%s/lib/root" pnd-dir (ext-v-full ext-v)))
  (setenv "ROOT_LIBRARIES"
	  (concat (format "-L%s/%s/lib/root" pnd-dir (ext-v-full ext-v))
		  " -lGui -lCore -lCint -lRIO -lNet -lHist -lGraf -lGraf3d"
		  " -lGpad -lTree -lRint -lPostscript -lMatrix -lPhysics -lMathCore -lThread"))
  (setenv "ROOT_INCLUDE_DIR" (format "%s/%s/include/root" pnd-dir (ext-v-full ext-v))))

(defun set-dynamic-load-path (path-var ext-v pnd-root-v)
  (if (not (string-match "panda" (getenv path-var)))
      (setenv path-var
	      (concat
	       (format "%s/%s/build/lib:" pnd-dir (pnd-root-v-full pnd-root-v))
	       (format "%s/%s/lib/root:" pnd-dir (ext-v-full ext-v))
	       (format "%s/%s/lib" pnd-dir (ext-v-full ext-v))
	       (if (and (getenv path-var) (not (string= (getenv path-var) "")))
		   (concat ":" (getenv path-var)))
	       ))))

(defun set-exec-path (ext-v)
  (if (not (string-match "panda" (getenv "PATH")))
      (setenv "PATH" (concat
		      (format "%s/%s/bin" pnd-dir (ext-v-full ext-v))
		      (if (and (getenv "PATH") (not (string= (getenv "PATH") "")))
			  (concat ":" (getenv "PATH")))))))

(defun env-pnd-root (ext-v pnd-root-v)
  (interactive)
  (setenv "Linux_Flavour_" "Darwin 13.4.0")
  (setenv "System_" "x86_64")
  (setenv "SIMPATH" (format "%s/%s" pnd-dir (ext-v-full ext-v)))
  (setenv "VMCWORKDIR" (format "%s/%s" pnd-dir (pnd-root-v-full pnd-root-v)))
  (setenv "FAIRLIBDIR" (format "%s/%s/build/lib" pnd-dir (pnd-root-v-full pnd-root-v)))
  (set-exec-path ext-v)
  (set-dynamic-load-path "DYLD_LIBRARY_PATH" ext-v pnd-root-v)
  (set-dynamic-load-path "LD_LIBRARY_PATH" ext-v pnd-root-v)
  (env-vmc ext-v)
  (env-geant-4-dat ext-v)
  (env-geant-4 ext-v)
  (env-geant-3 ext-v)
  (env-evt-gen ext-v)
  (env-root ext-v))

(setenv "PATH" "")
(setenv "LD_LIBRARY_PATH" "")
(setenv "DYLD_LIBRARY_PATH" "")
(env-pnd-root "apr13" "scrut14")
